name = "sbti-test"
main = ".open-next/worker.js"
compatibility_date = "2024-04-04"
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
NEXT_RUNTIME = "cloudflare"

[observability]
enabled = true
